# Generated by Django 5.2.4 on 2025-07-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
    ]
