# Generated by Django 5.2.4 on 2025-07-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={},
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CronogramaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.CharField(help_text='Ex: 6 h', max_length=50)),
                ('dias_da_semana', models.CharField(help_text='Ex: Monday, Wednesday', max_length=200)),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Cronograma da Disciplina',
                'verbose_name_plural': 'Cronogramas das Disciplinas',
            },
        ),
    ]
