# Generated by Django 5.2.4 on 2025-07-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_alter_disciplina_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cronogramadisciplina',
            name='carga_horaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cronogramadisciplina',
            name='dias_da_semana',
            field=models.CharField(max_length=200),
        ),
    ]
