# Generated by Django 5.2.4 on 2025-07-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_curso_alter_cronogramadisciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronogramadisciplina',
            options={'ordering': ['disciplina__nome'], 'verbose_name': 'Cronograma da Disciplina', 'verbose_name_plural': 'Cronogramas das Disciplinas'},
        ),
    ]
