# Generated by Django 5.2.4 on 2025-07-12 03:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_alter_cronogramadisciplina_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronogramadisciplina',
            options={'ordering': ['next_review'], 'verbose_name': 'Cronograma da Disciplina (Estudo Espaçado)', 'verbose_name_plural': 'Cronogramas das Disciplinas (Estudo Espaçado)'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AddField(
            model_name='cronogramadisciplina',
            name='ease_factor',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Fator de Facilidade (EF)'),
        ),
        migrations.AddField(
            model_name='cronogramadisciplina',
            name='interval_days',
            field=models.IntegerField(default=0, verbose_name='Intervalo (dias)'),
        ),
        migrations.AddField(
            model_name='cronogramadisciplina',
            name='last_reviewed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Última Revisão'),
        ),
        migrations.AddField(
            model_name='cronogramadisciplina',
            name='next_review',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Próxima Revisão'),
        ),
        migrations.AddField(
            model_name='cronogramadisciplina',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Contagem de Revisões'),
        ),
        migrations.AddField(
            model_name='cronogramadisciplina',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 12, 3, 17, 59, 275421, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cronogramadisciplina',
            name='carga_horaria',
            field=models.CharField(max_length=50, verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='cronogramadisciplina',
            name='dias_da_semana',
            field=models.CharField(max_length=200, verbose_name='Dias da Semana'),
        ),
        migrations.AlterField(
            model_name='cronogramadisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas_disciplina', to='disciplinas.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código da Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Disciplina'),
        ),
        migrations.AlterUniqueTogether(
            name='cronogramadisciplina',
            unique_together={('user', 'disciplina')},
        ),
    ]
