# Generated by Django 5.2.4 on 2025-07-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_alter_cronogramadisciplina_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cronogramadisciplina',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Horas de Estudo por Semana'),
        ),
        migrations.RemoveField(
            model_name='cronogramadisciplina',
            name='dias_da_semana',
        ),
        migrations.AddField(
            model_name='cronogramadisciplina',
            name='dias_da_semana',
            field=models.ManyToManyField(to='disciplinas.diasemana', verbose_name='Dias de Estudo'),
        ),
    ]
